package media

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"
)

// Suggestion is a single related-track recommendation used to power autoplay
// when a chat's queue drains. It mirrors the dicts returned by the Python bot's
// get_related_suggestions (youtube.py).
type Suggestion struct {
	VideoID  string
	Title    string
	Author   string
	Duration time.Duration
	URL      string
}

// WatchURL returns a canonical watch URL the normal resolver chain can play.
func (s Suggestion) WatchURL() string {
	if s.URL != "" {
		return s.URL
	}
	return "https://www.youtube.com/watch?v=" + s.VideoID
}

// RelatedResolver fetches related-music recommendations for a seed track,
// mirroring the Python bot: YouTube Music radio mix (/next with RDAMVM) as the
// primary source, then an InnerTube search fallback. It never returns the seed
// or any excluded video, so autoplay does not loop A -> B -> A.
type RelatedResolver struct {
	Client *http.Client
}

const youTubeMusicNextURL = "https://music.youtube.com/youtubei/v1/next?key="

var innerTubeClientRemix = map[string]any{
	"clientName":    "WEB_REMIX",
	"clientVersion": "1.20240101.01.00",
	"hl":            "en",
	"gl":            "US",
}

func (r *RelatedResolver) http() *http.Client {
	if r.Client != nil {
		return r.Client
	}
	return &http.Client{Timeout: 15 * time.Second}
}

// Related returns up to limit suggestions related to seed, skipping any video ID
// present in exclude (and the seed itself).
func (r *RelatedResolver) Related(ctx context.Context, seed Track, exclude map[string]struct{}, limit int) ([]Suggestion, error) {
	if limit <= 0 {
		limit = 5
	}
	seedID := seed.ID
	if seedID == "" {
		seedID = extractYouTubeVideoID(seed.OriginalInput)
	}
	if seedID == "" {
		seedID = extractYouTubeVideoID(seed.StreamURL)
	}
	if seedID == "" {
		return nil, errors.New("no seed video id for related lookup")
	}

	excluded := make(map[string]struct{}, len(exclude)+1)
	for id := range exclude {
		excluded[id] = struct{}{}
	}
	excluded[seedID] = struct{}{}

	var suggestions []Suggestion
	radio, radioErr := r.radio(ctx, seedID)
	for _, item := range radio {
		if item.VideoID == "" {
			continue
		}
		if _, skip := excluded[item.VideoID]; skip {
			continue
		}
		excluded[item.VideoID] = struct{}{}
		suggestions = append(suggestions, item)
		if len(suggestions) >= limit {
			return suggestions, nil
		}
	}

	// Fallback: top up with an InnerTube search when the radio mix was thin.
	query := strings.TrimSpace(seed.Title)
	if query == "" {
		query = "similar music to " + seedID
	}
	found, searchErr := r.search(ctx, query, limit*3)
	for _, item := range found {
		if item.VideoID == "" {
			continue
		}
		if _, skip := excluded[item.VideoID]; skip {
			continue
		}
		excluded[item.VideoID] = struct{}{}
		suggestions = append(suggestions, item)
		if len(suggestions) >= limit {
			break
		}
	}

	if len(suggestions) == 0 {
		// Last resort: relax exclusion so a live call is not dropped, keeping the
		// seed itself out (matches the Python fallback).
		for _, item := range radio {
			if item.VideoID == "" || item.VideoID == seedID {
				continue
			}
			suggestions = append(suggestions, item)
			if len(suggestions) >= limit {
				break
			}
		}
	}

	if len(suggestions) == 0 {
		if radioErr != nil {
			return nil, radioErr
		}
		if searchErr != nil {
			return nil, searchErr
		}
		return nil, errors.New("no related suggestions found")
	}
	return suggestions, nil
}

// radio fetches the YouTube Music autogenerated radio mix for a seed video.
func (r *RelatedResolver) radio(ctx context.Context, seedID string) ([]Suggestion, error) {
	payload := map[string]any{
		"context":    map[string]any{"client": innerTubeClientRemix},
		"videoId":    seedID,
		"playlistId": "RDAMVM" + seedID,
		"isAutomix":  true,
	}
	body, err := json.Marshal(payload)
	if err != nil {
		return nil, err
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodPost, youTubeMusicNextURL+innerTubeAPIKey, bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	request.Header.Set("Content-Type", "application/json")
	request.Header.Set("Referer", "https://music.youtube.com/")
	request.Header.Set("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")
	response, err := r.http().Do(request)
	if err != nil {
		return nil, err
	}
	defer response.Body.Close()
	if response.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("YouTube Music next returned HTTP %d", response.StatusCode)
	}
	var decoded any
	if err := json.NewDecoder(response.Body).Decode(&decoded); err != nil {
		return nil, err
	}
	return extractYTMusicTracks(decoded), nil
}

// search performs an InnerTube search and collects the video results, used as a
// fallback source of recommendations.
func (r *RelatedResolver) search(ctx context.Context, query string, limit int) ([]Suggestion, error) {
	client := innerTubeClients[0]
	payload := map[string]any{"context": map[string]any{"client": innerTubeClientPayload(client)}, "query": query}
	body, err := json.Marshal(payload)
	if err != nil {
		return nil, err
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodPost, innerTubeBaseURL+"search?key="+innerTubeAPIKey, bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	request.Header.Set("Content-Type", "application/json")
	request.Header.Set("X-YouTube-Client-Name", client.Header)
	request.Header.Set("X-YouTube-Client-Version", client.Version)
	request.Header.Set("User-Agent", client.UserAgent)
	response, err := r.http().Do(request)
	if err != nil {
		return nil, err
	}
	defer response.Body.Close()
	if response.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("InnerTube search returned HTTP %d", response.StatusCode)
	}
	var decoded any
	if err := json.NewDecoder(response.Body).Decode(&decoded); err != nil {
		return nil, err
	}
	tracks := extractYTMusicTracks(decoded)
	if len(tracks) > limit {
		tracks = tracks[:limit]
	}
	return tracks, nil
}

// extractYTMusicTracks walks a decoded InnerTube/YT Music response and collects
// every playlistPanelVideoRenderer and compactVideoRenderer it finds, matching
// the recursive extractor in youtube.py (_extract_ytm_tracks).
func extractYTMusicTracks(node any) []Suggestion {
	var out []Suggestion
	seen := make(map[string]struct{})
	var walk func(any)
	walk = func(current any) {
		switch value := current.(type) {
		case map[string]any:
			for _, key := range []string{"playlistPanelVideoRenderer", "compactVideoRenderer", "videoRenderer"} {
				renderer, ok := value[key].(map[string]any)
				if !ok {
					continue
				}
				item := suggestionFromRenderer(renderer)
				if item.VideoID == "" || item.Title == "" {
					continue
				}
				if _, dup := seen[item.VideoID]; dup {
					continue
				}
				seen[item.VideoID] = struct{}{}
				out = append(out, item)
			}
			for _, child := range value {
				walk(child)
			}
		case []any:
			for _, child := range value {
				walk(child)
			}
		}
	}
	walk(node)
	return out
}

func suggestionFromRenderer(renderer map[string]any) Suggestion {
	videoID, _ := renderer["videoId"].(string)
	item := Suggestion{VideoID: videoID}
	item.Title = extractRunsText(renderer["title"])
	item.Author = extractRunsText(renderer["shortBylineText"])
	if item.Author == "" {
		item.Author = extractRunsText(renderer["longBylineText"])
	}
	if item.Author == "" {
		item.Author = extractRunsText(renderer["ownerText"])
	}
	item.Duration = parseClockDuration(extractRunsText(renderer["lengthText"]))
	if videoID != "" {
		item.URL = "https://www.youtube.com/watch?v=" + videoID
	}
	return item
}

// extractRunsText reads a YouTube text node, which is either {"simpleText": ...}
// or {"runs": [{"text": ...}, ...]}.
func extractRunsText(node any) string {
	textNode, ok := node.(map[string]any)
	if !ok {
		return ""
	}
	if simple, ok := textNode["simpleText"].(string); ok {
		return simple
	}
	runs, ok := textNode["runs"].([]any)
	if !ok {
		return ""
	}
	var builder strings.Builder
	for _, raw := range runs {
		if run, ok := raw.(map[string]any); ok {
			if text, ok := run["text"].(string); ok {
				builder.WriteString(text)
			}
		}
	}
	return builder.String()
}

// parseClockDuration turns a "M:SS" or "H:MM:SS" length label into a Duration.
func parseClockDuration(value string) time.Duration {
	value = strings.TrimSpace(value)
	if value == "" {
		return 0
	}
	parts := strings.Split(value, ":")
	var total int64
	for _, part := range parts {
		n, err := strconv.ParseInt(strings.TrimSpace(part), 10, 64)
		if err != nil {
			return 0
		}
		total = total*60 + n
	}
	return time.Duration(total) * time.Second
}
